Global:
  Source: "config(local)"
  ChangeMe: "v3"

Director: log
JWT:
  signingKey: "xdream"
  ExpiresTime: 604800
  BufferTime: 86400
redis:
  db: 1
  addr: '127.0.0.1:6379'
#  password: ''

Etcd:
  Enable: true
  Address: "101.43.131.145"
  Port: 2379

Server:
  Name: "TiktokAPIServer"
  Address: "0.0.0.0"
  Port: 8088

Hertz:
  UseNetpoll: true
  Http2: 
    Enable: false
    DisableKeepalive: false
    ReadTimeout: "1m0s"
  Tls: 
    Enable: false
    CertFile: ""
    KeyFile: ""
    ALPN: true

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"
zap:
  Level: 'info'
  Format: 'console'
  Prefix: '[RZ-WORK-FLOW]'
  Director: 'log/api'
  LinkName: 'latest_log'
  ShowLine: true
  EncodeLevel: 'LowercaseColorLevelEncoder'
  StacktraceKey: 'stacktrace'
  LogInConsole: true