Global:
  Source: "config(local)"
  ChangeMe: "v3"
JWT:
  signingKey: "xdream"
  ExpiresTime: 604800
  BufferTime: 86400

Etcd:
  Address: "101.43.131.145"
  Port: 2379

Server:
  Name: "TiktokFavoriteServer"
  Address: "127.0.0.1"
  Port: 8085

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"
mysql:
  Path: '101.43.131.145:3306'
  Config: 'charset=utf8mb4&parseTime=True&loc=Local'
  DbName: 'tik_tok'
  Username: 'root'
  Password: '257518'
  log-mode: 'debug'
  log-zap: false
  maxIdleConns: 10 # 空闲连接池中连接的最大数量
  maxOpenConns: 100 # 打开数据库连接的最大数量
zap:
  Level: 'info'
  Format: 'console'
  Prefix: '[RZ-WORK-FLOW]'
  Director: 'cmd/favorite_service/log'
  LinkName: 'latest_log'
  ShowLine: true
  EncodeLevel: 'LowercaseColorLevelEncoder'
  StacktraceKey: 'stacktrace'
  LogInConsole: true