Global:
  Source: "config(local)"
  ChangeMe: "v3"
mysql:
  Path: '101.43.131.145:3306'
  Config: 'charset=utf8mb4&parseTime=True&loc=Local'
  DbName: 'tik_tok'
  Username: 'root'
  Password: 'root'
  log-mode: '257518'
  log-zap: false
  maxIdleConns: 10 # 空闲连接池中连接的最大数量
  maxOpenConns: 100 # 打开数据库连接的最大数量
JWT:
  signingKey: "xdream"
  ExpiresTime: 604800
  BufferTime: 86400

Etcd:
  Address: "101.43.131.145"
  Port: 2379

Server:
  Name: "TiktokPublishServer"
  Address: "127.0.0.1"
  Port: 8084

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"
ftp:
  address: 101.43.131.145
  port: 21
  account: HKTXY
  password: 15770704524TXY
  getport: 81
zap:
  Level: 'info'
  Format: 'console'
  Prefix: '[RZ-WORK-FLOW]'
  Director: 'log/publish_service'
  LinkName: 'latest_log'
  ShowLine: true
  EncodeLevel: 'LowercaseColorLevelEncoder'
  StacktraceKey: 'stacktrace'
  LogInConsole: true
Minio:
  Endpoint: 101.43.131.145:9090
  AccessKeyId: tiktokMinio
  SecretAccessKey: tiktokMinio
  UseSSL: false
  VideoBucketName : tiktok-video
qiniu:
  zone: 'ZoneHuanan'
  bucket: 'xdream-tiktok'
  imgPath: 'rqizbp4n3.hn-bkt.clouddn.com'
  UseHttps: false
  AccessKey: 'AekmSg5xsKAO4q5evKaXQ-SXOI4i6v0hJNnb5OZM'
  SecretKey: 'BUk_1FjCi4obxrTR7ivqzB0EIYYPcHWIzQeke2yB'
  UseCdnDomains: false