Global:
  Source: "config(local)"
  ChangeMe: "v3"
mysql:
  Path: '101.43.131.145:3306'
  Config: 'charset=utf8mb4&parseTime=True&loc=Local'
  DbName: 'tik_tok'
  Username: 'root'
  Password: '257518'
  log-mode: 'debug'
  log-zap: false
  maxIdleConns: 10 # 空闲连接池中连接的最大数量
  maxOpenConns: 100 # 打开数据库连接的最大数量
JWT:
  signingKey: "xdream"
  ExpiresTime: 604800
  BufferTime: 86400

Etcd:
  Address: "101.43.131.145."
  Port: 2379
redis:
  db: 1
  addr: '127.0.0.1:6379'
#  password: ''
Password:
  key: "xdream"
Server:
  Name: "TiktokUserServer"
  Address: "127.0.0.1"
  Port: 8888
  Argon2ID:
    Memory: 64*1024
    Iterations: 3
    Parallelism: 2
    SaltLength: 16
    keyLength: 32

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"
zap:
  Level: 'info'
  Format: 'console'
  Prefix: '[RZ-WORK-FLOW]'
  Director: 'log/user_service'
  LinkName: 'latest_log'
  ShowLine: true
  EncodeLevel: 'LowercaseColorLevelEncoder'
  StacktraceKey: 'stacktrace'
  LogInConsole: true